countries: ["USA","GBR","DEU","FRA","RUS","CHN","IND","BRA","ZAF","AUS","JPN","CAN"]
start_year: 1996
end_year: 2024
indicators:
  S_proxy: "GE.EST"
  N_proxy: "PV.EST"
  R_proxy: "IT.NET.USER.ZS"
  Crisis:  "FP.CPI.TOTL.ZG"
